apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-aws-monitor
  namespace: argocd
spec:
  project: gitops-project
  source:
    repoURL: https://github.com/DXNOAM/devops-course-app-June-2026.git
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
